apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: example
build:
  local:
    concurrency: 1
  artifacts:
    - image: example
      ko: {}
        # flags:
        # - -v
        # fromImage: gcr.io/distroless/base:debug-nonroot
        # dependencies:
        #   paths:
        #     - "**/*"
        #     - go.mod
deploy:
  kustomize:
    paths:
    - config/overlays/dev

