apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-ingress

generatorOptions:
  disableNameSuffixHash: true

resources:
- namespace.yaml
- rbac.yaml
- config.yaml
- deployment.yaml
- ingressclass.yaml
- service.yaml
- webhook.yaml
